source :gemcutter

gem 'sinatra', :require => 'sinatra/base'
gem 'thin', '~> 1.3'
gem 'pg'
gem 'sinatra-activerecord'
gem 'google-api-client', '>= 0.4.4', :require => 'google/api_client'


group :development do
  gem 'rake'
  gem 'sqlite3-ruby'
end

